openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
components:
  schemas:
    ProductDto:
      title: ProductDto
      x-stoplight:
        id: codfi1lt16bbm
      type: object
      description: ''
      properties:
        id:
          type: integer
          format: int64
        '':
          type: string
        price:
          type: number
          format: double
        category:
          $ref: '#/components/schemas/CategoryDto'
    CategoryDto:
      title: CategoryDto
      x-stoplight:
        id: xr22rfqjkkkji
      type: object
      properties:
        id:
          type: integer
          format: int64
        '':
          type: string
        poducts:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
