openapi: 3.0.1
paths:
  /api/categories:
    post:
      tags:
        - category-controller
      summary: ''
      operationId: createCategory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDto'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDto'
            examples:
              example-1:
                value:
                  id: 0
                  '': string
                  products:
                    - id: 0
                      name: string
                      price: 0
                      data: {}
    parameters: []
  /api/products/search:
    get:
      summary: Your GET endpoint
      tags:
        - product-controller
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
      operationId: searchProducts
      parameters:
        - schema:
            type: integer
          in: query
          name: page
        - schema:
            type: integer
          in: query
          name: size
        - schema:
            type: string
          in: query
          name: sort
        - schema:
            type: integer
            format: int64
          in: query
          name: id
        - schema:
            type: string
          in: query
          name: name
        - schema:
            type: string
          in: query
          name: category.name
        - schema:
            type: array
            items:
              type: number
              format: double
          in: query
          name: price
    parameters: []
  /api/products:
    post:
      tags:
        - product-controller
      summary: ''
      operationId: createProduct
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDto'
    parameters: []
  '/api/products/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - product-controller
      summary: ''
      operationId: modify Product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./catalog-openapi.yaml#/components/schemas/ProductDto
    delete:
      tags:
        - product-controller
      summary: ''
      operationId: delete Product
      responses:
        '200':
          description: OK
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
components:
  schemas:
    ProductDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: double
        data:
          $ref: '#/components/schemas/CategoryDto'
      title: ''
    CategoryDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
