server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    tokenlib:
      keypaths:
        private: /pem/private.pem       
        public: /pem/public.pem
#hu:
#  webuni:
#    tokenlib:
#      keypaths:
#        private: /Users/gabor/Downloads/private.pem
#        public: /Users/gabor/Downloads/public.pem