create sequence hibernate_sequence start 1 increment 1;
create table course (id int8 not null, name varchar(255), semester_type int4, year int4 not null, primary key (id));
create table course_aud (id int8 not null, rev int4 not null, revtype int2, name varchar(255), semester_type int4, year int4, primary key (id, rev));
create table course_students (courses_id int8 not null, students_id int8 not null, primary key (courses_id, students_id));
create table course_students_aud (rev int4 not null, courses_id int8 not null, students_id int8 not null, revtype int2, primary key (rev, courses_id, students_id));
create table course_teachers (courses_id int8 not null, teachers_id int8 not null, primary key (courses_id, teachers_id));
create table course_teachers_aud (rev int4 not null, courses_id int8 not null, teachers_id int8 not null, revtype int2, primary key (rev, courses_id, teachers_id));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
create table special_day_aud (id int4 not null, rev int4 not null, revtype int2, source_day date, target_day date, primary key (id, rev));
create table special_day (id int4 not null, source_day date, target_day date, primary key (id));
create table student (balance int4 not null, cid int8 not null, semester int4 not null, ufsc int4 not null, id int8 not null, primary key (id));
create table student_aud (id int8 not null, rev int4 not null, balance int4, cid int8, semester int4, ufsc int4, primary key (id, rev));
create table student_user (username varchar(255) not null, facebook_id varchar(255), password varchar(255), primary key (username));
create table student_user_roles (student_user_username varchar(255) not null, roles varchar(255));
create table teacher (id int8 not null, primary key (id));
create table teacher_aud (id int8 not null, rev int4 not null, primary key (id, rev));
create table timetable (id int8 not null, day_of_week int4, end_time time, start_time time, course_id int8, primary key (id));
create table timetable_aud (id int8 not null, rev int4 not null, revtype int2, day_of_week int4, end_time time, start_time time, course_id int8, primary key (id, rev));
create table university_user_aud (id int8 not null, rev int4 not null, revtype int2, birthdate date, facebook_id varchar(255), google_id varchar(255), name varchar(255), password varchar(255), username varchar(255), primary key (id, rev));
create table university_user (id int8 not null, birthdate date, facebook_id varchar(255), google_id varchar(255), name varchar(255), password varchar(255), username varchar(255), primary key (id));
alter table if exists course_aud add constraint FK7wota7b9g9bu9by751v8r8j65 foreign key (rev) references revinfo;
alter table if exists course_students add constraint FK532dg5ikp3dvbrbiiqefdoe6m foreign key (students_id) references student;
alter table if exists course_students add constraint FKh6irfl8rj4jgb3xrlyxsr2bdk foreign key (courses_id) references course;
alter table if exists course_students_aud add constraint FK53xchn8n2cpmyfr1tvaa7ndvv foreign key (rev) references revinfo;
alter table if exists course_teachers add constraint FKe3n62rwx3uc1yucgkmw6gjkm5 foreign key (teachers_id) references teacher;
alter table if exists course_teachers add constraint FK5ntgqv47cbgq8s0la1myeg5ly foreign key (courses_id) references course;
alter table if exists course_teachers_aud add constraint FKhxsr1pho67e2es9pv4v0js9l9 foreign key (rev) references revinfo;
alter table if exists special_day_aud add constraint FKke1jl33xwvveiw7wvsmupf177 foreign key (rev) references revinfo;
alter table if exists student add constraint FK9wqqrdwh5j5tkja9ix5n35671 foreign key (id) references university_user;
alter table if exists student_aud add constraint FKct7l5aou36vau0j2ves7vd6r5 foreign key (id, rev) references university_user_aud;
alter table if exists student_user_roles add constraint FKciq0uu7ofpj8a3ax40eghkj9v foreign key (student_user_username) references student_user;
alter table if exists teacher add constraint FK3ishnayracolicixocno05kmt foreign key (id) references university_user;
alter table if exists teacher_aud add constraint FKc7h10qomjgvthn1bnh32kv44f foreign key (id, rev) references university_user_aud;
alter table if exists timetable add constraint FKrdljqbhvm52vnxoy3xapbkho0 foreign key (course_id) references course;
alter table if exists timetable_aud add constraint FK2dn7jd07tn6j62sygvaba54k0 foreign key (rev) references revinfo;
alter table if exists university_user_aud add constraint FK3kui2v2p71dteg77ff3dwi2lo foreign key (rev) references revinfo;
