server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    tokenlib:
      keypaths:
        public: /pem/public.pem
spring:
  cloud:
    gateway:
      routes:
      - id: catalog-service-webshop
        uri: lb://catalog-service-webshop
        predicates:
        - Path=/catalog/**
        filters:
        - RewritePath=/catalog(?<segment>/?.*), /api$\{segment}
      - id: order-service-webshop
        uri: lb://order-service-webshop
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order(?<segment>/?.*), /api$\{segment}
      - id: user-service-webshop
        uri: lb://users-service-webshop
        predicates:
        - Path=/users/**
        filters:
        - RewritePath=/users(?<segment>/?.*), /api$\{segment}